export interface IEmotion {
  emotion: string;
  categories: (
    | 'Colère'
    | 'Jalousie / Envie'
    | 'Honte'
    | 'Dégoût'
    | 'Peur'
    | 'Tristesse'
    | 'Surprise'
    | 'Joie'
    | 'Amour'
  )[];
}

export const EMOTIONS: IEmotion[] = [
  { emotion: 'A bout', categories: ['Colère'] },
  { emotion: 'Abattu', categories: ['Tristesse'] },
  { emotion: 'Accablé', categories: ['Tristesse'] },
  { emotion: 'Affligé', categories: ['Peur', 'Tristesse'] },
  { emotion: 'Agacé', categories: ['Colère'] },
  { emotion: 'Agité', categories: ['Colère'] },
  { emotion: 'Aigri', categories: ['Jalousie / Envie'] },
  { emotion: 'Alarmé', categories: ['Colère'] },
  { emotion: 'Amer', categories: ['Colère', 'Jalousie / Envie'] },
  { emotion: 'Amoureux', categories: ['Amour'] },
  { emotion: 'Amusé', categories: ['Surprise'] },
  { emotion: 'Anéanti', categories: ['Dégoût'] },
  { emotion: 'Anxieux', categories: ['Peur'] },
  { emotion: 'Apaisé', categories: ['Joie'] },
  { emotion: 'Attendri', categories: ['Amour'] },
  { emotion: 'Blessé', categories: ['Dégoût', 'Tristesse'] },
  { emotion: 'Bouleversé', categories: ['Tristesse'] },
  { emotion: 'Calme', categories: ['Joie'] },
  { emotion: 'Chagriné', categories: ['Tristesse'] },
  { emotion: 'Charmé', categories: ['Amour'] },
  { emotion: 'Choqué', categories: ['Peur'] },
  { emotion: 'Comblé', categories: ['Amour'] },
  { emotion: 'Confiant', categories: ['Joie'] },
  { emotion: 'Confus', categories: ['Honte', 'Peur'] },
  { emotion: 'Consterné', categories: ['Colère'] },
  { emotion: 'Content', categories: ['Joie'] },
  { emotion: 'Convoiter', categories: ['Jalousie / Envie'] },
  { emotion: 'Coupable', categories: ['Honte'] },
  { emotion: 'Craintif', categories: ['Peur'] },
  { emotion: 'Crispé', categories: ['Peur'] },
  { emotion: 'Curieux', categories: ['Surprise'] },
  { emotion: 'De bonne humeur', categories: ['Joie'] },
  { emotion: 'Décontracté', categories: ['Joie'] },
  { emotion: 'Déçu', categories: ['Tristesse'] },
  { emotion: 'Défait', categories: ['Honte'] },
  { emotion: 'Dégoutté', categories: ['Dégoût'] },
  { emotion: 'Délivré', categories: ['Joie'] },
  { emotion: 'Démuni', categories: ['Tristesse'] },
  { emotion: 'Désespéré', categories: ['Tristesse'] },
  { emotion: 'Désillusionné', categories: ['Dégoût'] },
  { emotion: 'Désireux', categories: ['Jalousie / Envie'] },
  { emotion: 'Désolé', categories: ['Tristesse'] },
  { emotion: 'Détaché', categories: ['Dégoût'] },
  { emotion: 'Écoeuré', categories: ['Dégoût'] },
  { emotion: 'Effrayé', categories: ['Peur'] },
  { emotion: 'Embarrassé', categories: ['Honte'] },
  { emotion: 'Émerveillé', categories: ['Surprise'] },
  { emotion: 'Ému', categories: ['Amour'] },
  { emotion: 'En Colère', categories: ['Colère'] },
  { emotion: 'En sécurité', categories: ['Amour'] },
  { emotion: 'Enchanté', categories: ['Amour'] },
  { emotion: 'Encouragé', categories: ['Amour'] },
  { emotion: 'Énervé', categories: ['Colère'] },
  { emotion: 'Enjoué', categories: ['Joie'] },
  { emotion: 'Ennuyé', categories: ['Honte'] },
  { emotion: 'Envieux', categories: ['Jalousie / Envie'] },
  { emotion: 'Étonné', categories: ['Surprise'] },
  { emotion: 'Éveillé', categories: ['Surprise'] },
  { emotion: 'Exaspéré', categories: ['Colère'] },
  { emotion: 'Excédé', categories: ['Colère'] },
  { emotion: 'Excité', categories: ['Surprise'] },
  { emotion: 'Exigeant', categories: ['Jalousie / Envie'] },
  { emotion: 'Fâché', categories: ['Colère', 'Dégoût'] },
  { emotion: 'Fatigué', categories: ['Dégoût'] },
  { emotion: 'Fragile', categories: ['Peur'] },
  { emotion: 'Furieux', categories: ['Colère'] },
  { emotion: 'Gai', categories: ['Joie'] },
  { emotion: 'Gêné', categories: ['Honte'] },
  { emotion: 'Gourmand', categories: ['Jalousie / Envie'] },
  { emotion: 'Haineux', categories: ['Colère'] },
  { emotion: 'Hilare', categories: ['Surprise'] },
  { emotion: 'Honteux', categories: ['Honte'] },
  { emotion: 'Horrifié', categories: ['Dégoût'] },
  { emotion: 'Humilié', categories: ['Honte'] },
  { emotion: 'Inquiet', categories: ['Peur'] },
  { emotion: 'Insatisfait', categories: ['Peur'] },
  { emotion: 'Insécurité', categories: ['Jalousie / Envie'] },
  { emotion: 'Inspiré', categories: ['Surprise'] },
  { emotion: 'Intéressé', categories: ['Surprise'] },
  { emotion: 'Irrité', categories: ['Colère'] },
  { emotion: 'Jaloux', categories: ['Jalousie / Envie'] },
  { emotion: 'Joyeux', categories: ['Jalousie / Envie', 'Joie'] },
  { emotion: 'Lassé', categories: ['Tristesse'] },
  { emotion: 'Malheureux', categories: ['Tristesse'] },
  { emotion: 'Mécontent', categories: ['Colère'] },
  { emotion: 'Méfiant', categories: ['Peur'] },
  { emotion: 'Menacé', categories: ['Jalousie / Envie'] },
  { emotion: 'Optimiste', categories: ['Amour'] },
  { emotion: 'Paisible', categories: ['Amour'] },
  { emotion: 'Paralysé', categories: ['Peur'] },
  { emotion: 'Possessif', categories: ['Jalousie / Envie'] },
  { emotion: 'Protecteur', categories: ['Jalousie / Envie'] },
  { emotion: 'Rancunier', categories: ['Jalousie / Envie'] },
  { emotion: 'Rassuré', categories: ['Amour'] },
  { emotion: 'Ravi', categories: ['Amour'] },
  { emotion: 'Refus de croire', categories: ['Jalousie / Envie'] },
  { emotion: 'Satisfait', categories: ['Joie'] },
  { emotion: 'Secoué', categories: ['Honte'] },
  { emotion: 'Serein', categories: ['Joie'] },
  { emotion: 'Sidéré', categories: ['Surprise'] },
  { emotion: 'Soupçonneux', categories: ['Jalousie / Envie'] },
  { emotion: 'Terrifié', categories: ['Peur'] },
  { emotion: 'Triste', categories: ['Tristesse'] },
  { emotion: 'Vexé', categories: ['Colère'] },
  { emotion: 'Vulnérable', categories: ['Jalousie / Envie'] },
  { emotion: "Vert d'envie", categories: ['Jalousie / Envie'] },
];
